---
- name: Create file with specific content
  hosts: all
  gather_facts: false

  tasks:
    - name: Create file
      shell:
        "ip addr"
      register: os_info
    
    - debug:
        msg: "{{os_info.stdout_lines}}"      