---
- name: Create file with specific content
  hosts: test
  gather_facts: false

  tasks:
    - name: Create file
      ansible.builtin.file:
        path: "/home/ubuntu/file.txt"
        state: touch

    - name: Add content to file
      ansible.builtin.lineinfile:
        path: "/home/ubuntu/file.txt"
        line: "This is for AWX test"